name: Build Flet APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Flet and Dependencies
        run: |
          pip install pandas flet
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Flet Build APK
        run: |
          # Usiamo python -m flet per essere sicuri che lo trovi
          python -m flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: typo-app-android
          path: build/apk/*.apk
